global:
  scrape_interval: 20s
  scrape_timeout: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
          
rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['prometheus:9090']
  
  - job_name: node-exporter
    static_configs:
    - targets: ['node-exporter:9100']
    # tls_config:
      # insecure_skip_verify: true

  - job_name: cadvisor
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: windows-exporter
    static_configs:
    - targets: ['host.docker.internal:9182']